/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miniForm;

import DAO.Duc.TaiKhoanDao;
import DAO.maXacNhanDao;
import Helper.Duc.unlityHelper;
import Helper.Duc.dialogHelper;
import static java.awt.Color.pink;
import javax.swing.JOptionPane;
import model.MaXacNhan;
import model.TaiKhoanMode;
import sun.text.Normalizer;

/**
 *
 * @author CHIEN
 */
public class DoiMatKhau extends javax.swing.JFrame {

    MaXacNhan xn = new MaXacNhan();
    maXacNhanDao daoxn = new maXacNhanDao();
    TaiKhoanDao dao = new TaiKhoanDao();

    public DoiMatKhau(String ma) {
        initComponents();
        setLocationRelativeTo(null);
        String ma1 = ma;
        lbEmail.setText(ma1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtMkMoi = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        bnXacNhan = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtNhapLaiMk = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtMaXacNhan = new javax.swing.JTextField();
        lbEmail = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBackground(new java.awt.Color(107, 70, 52));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Đổi mật khẩu mới");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nhập mật khẩu mới");

        txtMkMoi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtMkMoi.setForeground(new java.awt.Color(107, 70, 52));
        txtMkMoi.setVerifyInputWhenFocusTarget(false);
        txtMkMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMkMoiActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(107, 70, 52));
        jPanel3.setLayout(new java.awt.GridLayout(1, 2, 20, 10));

        jButton1.setBackground(new java.awt.Color(201, 0, 15));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/huy.png"))); // NOI18N
        jButton1.setText("Hủy");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);

        bnXacNhan.setBackground(new java.awt.Color(1, 161, 79));
        bnXacNhan.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bnXacNhan.setForeground(new java.awt.Color(255, 255, 255));
        bnXacNhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/dangNhap.png"))); // NOI18N
        bnXacNhan.setText("Xác nhận");
        bnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnXacNhanActionPerformed(evt);
            }
        });
        jPanel3.add(bnXacNhan);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nhập lại mật khẩu");

        txtNhapLaiMk.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtNhapLaiMk.setForeground(new java.awt.Color(107, 70, 52));
        txtNhapLaiMk.setVerifyInputWhenFocusTarget(false);
        txtNhapLaiMk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNhapLaiMkActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nhập mã xác nhận");

        txtMaXacNhan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtMaXacNhan.setForeground(new java.awt.Color(107, 70, 52));
        txtMaXacNhan.setVerifyInputWhenFocusTarget(false);
        txtMaXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaXacNhanActionPerformed(evt);
            }
        });

        lbEmail.setBackground(new java.awt.Color(255, 255, 255));
        lbEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbEmail.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtMkMoi, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNhapLaiMk, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaXacNhan, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(20, 20, 20))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMkMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNhapLaiMk, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel5)
                .addGap(10, 10, 10)
                .addComponent(txtMaXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnXacNhanActionPerformed
        if (unlityHelper.checkNullText(txtMkMoi)) {
            if (unlityHelper.checkNullText(txtNhapLaiMk)) {
                if (unlityHelper.checkNullText(txtMaXacNhan)) {
                    if(checkmaXn()){
                    this.update();
                }
                
            }
        }

        }
    }//GEN-LAST:event_bnXacNhanActionPerformed

    private void txtMaXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaXacNhanActionPerformed

    }//GEN-LAST:event_txtMaXacNhanActionPerformed

    private void txtNhapLaiMkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNhapLaiMkActionPerformed

    }//GEN-LAST:event_txtNhapLaiMkActionPerformed

    private void txtMkMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMkMoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMkMoiActionPerformed

    public void update() {
        TaiKhoanMode model = getModel();
        String confirm = new String(txtNhapLaiMk.getText());
        if (!confirm.equals(model.getMatKhau())) {
            txtNhapLaiMk.setBackground(pink);
            JOptionPane.showMessageDialog(this, "Xác nhận mật khẩu không đúng!");
        } else {
            try {
                dao.doimk(model);
                dispose();

            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    TaiKhoanMode getModel() {
        TaiKhoanMode tk = new TaiKhoanMode();
        tk.setEmail(lbEmail.getText());
        tk.setMatKhau(new String(txtMkMoi.getText()));

        return tk;
    }

    public boolean checkmaXn() {
        String maxn = txtMaXacNhan.getText();
        try {
            xn = daoxn.findByMaXacNhan(maxn);
            if (xn != null) {
                JOptionPane.showMessageDialog(this, "Cập nhật thành công!");
                return true;
            } else {
                dialogHelper.alert(this, "Mã xác nhận không hợp lệ");
                return false;
            }
        } catch (Exception e) {
        }
        return true;
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(DoiMatKhau.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new DoiMatKhau().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnXacNhan;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JTextField txtMaXacNhan;
    private javax.swing.JTextField txtMkMoi;
    private javax.swing.JTextField txtNhapLaiMk;
    // End of variables declaration//GEN-END:variables
}
