/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miniForm;

import DAO.monAnDao;
import Helper.ChuyenDoi;
import Helper.shareHelper;
import Helper.unlityHelper;
import helper.dialogHelper;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import model.DanhMuc_duc;
import model.MonAn;

/**
 *
 * @author ducmc
 */
public class LoadMonAn extends javax.swing.JPanel {

    JFileChooser fileChooser = new JFileChooser();
    monAnDao dao = new monAnDao();
    MonAn monAn = new MonAn();
    String maHD;

    public LoadMonAn(MonAn mon) {
        initComponents();
        monAn = mon;
        filltoForm();

    }

    public void filltoForm() {
        ImageIcon img = new ImageIcon("src\\HinhAnh\\" + monAn.getHinhAnh());
        Image im = img.getImage();
        ImageIcon icon = new ImageIcon(im.getScaledInstance(300, 200, im.SCALE_SMOOTH));
        LbAnhSp.setIcon(icon);

        txtTenMon.setText(monAn.getTenMon());
        txtGiaMon.setText(ChuyenDoi.chuyenDoiTien(monAn.getDonGia()));
        lbMaMon.setText(String.valueOf(monAn.getMaMon()));

    }

//    MonAn setModel() {
//       mad.select(tenDanhMuc, "");
//        MonAn model = new MonAn();
//        txtTenMon.setText(model.getTenMon());
//        txtGiaMon.setText(model.getMaMon() + "");
//        lbMaMon.setText("Mã món : " + model.getMaMon());
//        if (model.getHinhAnh() != null) {
//            LbAnhSp.setIcon(shareHelper.readLogo(model.getHinhAnh()));
//            /*
//            ImageIcon readLogo(String tenFile) đọc file trong thư mục logos theo tên file trả về ImageIcon
//            void setIcon(ImageIcon icon) set Icon cho lbl
//             */
//        } else {
//            LbAnhSp.setIcon(shareHelper.readLogo("noImage.png"));
//        }
//        return model;
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LbAnhSp = new javax.swing.JLabel();
        txtTenMon = new javax.swing.JTextField();
        txtGiaMon = new javax.swing.JTextField();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        lbMaMon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(300, 350));
        setMinimumSize(new java.awt.Dimension(300, 350));
        setPreferredSize(new java.awt.Dimension(300, 350));
        setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        LbAnhSp.setMaximumSize(new java.awt.Dimension(280, 200));
        LbAnhSp.setMinimumSize(new java.awt.Dimension(280, 200));
        LbAnhSp.setPreferredSize(new java.awt.Dimension(280, 200));
        LbAnhSp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbAnhSpMouseClicked(evt);
            }
        });

        txtTenMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenMonActionPerformed(evt);
            }
        });

        btnSua.setText("SỬA");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("XÓA");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        lbMaMon.setBackground(new java.awt.Color(255, 255, 255));
        lbMaMon.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        lbMaMon.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tên món:");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Giá món:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtGiaMon, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                    .addComponent(txtTenMon)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbMaMon, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LbAnhSp, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LbAnhSp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGiaMon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbMaMon, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        add(jPanel1);
    }// </editor-fold>//GEN-END:initComponents

    private void txtTenMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenMonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenMonActionPerformed

      
    

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        if (unlityHelper.checkMoney(txtGiaMon)) {
            
            update();
            
            

        }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void LbAnhSpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbAnhSpMouseClicked
        this.selectImage();
    }//GEN-LAST:event_LbAnhSpMouseClicked

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        this.delete();
    }//GEN-LAST:event_btnXoaActionPerformed
    public void delete() {

        if (dialogHelper.confirm(this, "Bạn có muốn xóa hay không?")) {
            String maMa = lbMaMon.getText();
            try {
                dao.delete(maMa);
                dialogHelper.alert(this, "Xóa thành công");
            } catch (Exception e) {
                dialogHelper.alert(this, "Lỗi xóa");
            }
        }

    }

    MonAn getModel() {
        MonAn model = new MonAn();
        model.setTenMon(txtTenMon.getText());
        model.setDonGia(Double.valueOf(txtGiaMon.getText()));
        model.setHinhAnh(LbAnhSp.getToolTipText());    //lấy tên hình  . -Tôi bị lỗi phần load này chiến xử lí cho tôi mới nhaa . Cảm ơn ông nhiều nhaaa
        //  model.setHinhAnh(LbAnhSp.getText().toLowerCase() + ".JPG");
        model.setMaMon(Integer.valueOf(lbMaMon.getText()));
        return model;
    }

    public void update() {
        MonAn model = getModel();
        try {
            dao.update(model);
            dialogHelper.alert(this, "Sửa sản phẩm thành công");
        } catch (Exception e) {
            dialogHelper.alert(this, "Sửa sản phẩm thất bại");
            e.printStackTrace();
        }

    }

    void selectImage() {
        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) { //nếu người dùng đã chọn đc file
            File file = fileChooser.getSelectedFile();    //lấy file người dùng chọn
            if (shareHelper.saveLogo(file)) {  //sao chép file đã chọn thư mục 
                // Hiển thị hình lên form
                LbAnhSp.setIcon(shareHelper.readLogo(file.getName())); //file.getName(); lấy tên của file
                //  monAn.setHinhAnh((LbAnhSp.setIcon(shareHelper.readLogo(file.getName()))));
                //ImageIcon readLogo(String tenFile) đọc file trong thư mục logos theo tên file trả về ImageIcon
                //void setIcon(ImageIcon icon) set Icon cho lbl
                LbAnhSp.setToolTipText(file.getName());
            }
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LbAnhSp;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnXoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbMaMon;
    private javax.swing.JTextField txtGiaMon;
    private javax.swing.JTextField txtTenMon;
    // End of variables declaration//GEN-END:variables
}
