/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miniForm;

import DAO.BanHangDao;
import DAO.danhMucDao;
import DAO.monAnDao;
import Helper.shareHelper;
import Helper.unlityHelper;
import helper.dialogHelper;
import java.io.File;
import javax.smartcardio.CommandAPDU;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import model.MonAn;
import model.DanhMuc_duc;

/**
 *
 * @author CHIEN
 */
public class ThemMonAn extends javax.swing.JFrame {

    JFileChooser fileChooser = new JFileChooser();
    monAnDao dao = new monAnDao();

//    DefaultComboBoxModel comBoMode;
    DefaultComboBoxModel comBoDanhMuc;
    danhMucDao dmd = new danhMucDao();

    /**
     * Creates new form ThemMonAn
     */
    public ThemMonAn() {
        initComponents();
        setLocationRelativeTo(null);
        
        loadDataToComBoDM();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbHinh = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTenMon = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CbDanhMuc = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtGiaBan = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        BtnHuy = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(700, 600));
        setUndecorated(true);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBackground(new java.awt.Color(107, 70, 52));
        jPanel1.setMaximumSize(new java.awt.Dimension(700, 600));
        jPanel1.setMinimumSize(new java.awt.Dimension(700, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 600));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setMaximumSize(new java.awt.Dimension(250, 250));
        jPanel2.setMinimumSize(new java.awt.Dimension(250, 250));
        jPanel2.setPreferredSize(new java.awt.Dimension(250, 250));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        lbHinh.setMaximumSize(new java.awt.Dimension(250, 250));
        lbHinh.setMinimumSize(new java.awt.Dimension(250, 250));
        lbHinh.setPreferredSize(new java.awt.Dimension(250, 250));
        lbHinh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbHinhMouseClicked(evt);
            }
        });
        jPanel2.add(lbHinh);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Thêm món");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Tên món");

        txtTenMon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTenMon.setForeground(new java.awt.Color(107, 70, 52));
        txtTenMon.setVerifyInputWhenFocusTarget(false);
        txtTenMon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenMonActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Danh mục món");

        CbDanhMuc.setBackground(new java.awt.Color(204, 204, 255));
        CbDanhMuc.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        CbDanhMuc.setForeground(new java.awt.Color(107, 70, 52));
        CbDanhMuc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));
        CbDanhMuc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CbDanhMucItemStateChanged(evt);
            }
        });
        CbDanhMuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbDanhMucActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Giá bán");

        txtGiaBan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtGiaBan.setForeground(new java.awt.Color(107, 70, 52));
        txtGiaBan.setVerifyInputWhenFocusTarget(false);

        jPanel3.setBackground(new java.awt.Color(107, 70, 52));
        jPanel3.setLayout(new java.awt.GridLayout(2, 1, 20, 30));

        BtnHuy.setBackground(new java.awt.Color(201, 0, 15));
        BtnHuy.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        BtnHuy.setForeground(new java.awt.Color(255, 255, 255));
        BtnHuy.setText("Hủy");
        BtnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnHuyActionPerformed(evt);
            }
        });
        jPanel3.add(BtnHuy);

        btnThem.setBackground(new java.awt.Color(1, 161, 79));
        btnThem.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        jPanel3.add(btnThem);

        jPanel4.setBackground(new java.awt.Color(107, 70, 52));
        jPanel4.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        jLabel2.setBackground(new java.awt.Color(107, 70, 52));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/phache2.png"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(380, 230));
        jLabel2.setMinimumSize(new java.awt.Dimension(380, 230));
        jLabel2.setPreferredSize(new java.awt.Dimension(380, 230));
        jPanel4.add(jLabel2);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTenMon, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtGiaBan, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(CbDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1))
                        .addGap(0, 134, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3)
                        .addGap(10, 10, 10)
                        .addComponent(txtTenMon, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4)
                        .addGap(10, 10, 10)
                        .addComponent(CbDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel5)
                        .addGap(10, 10, 10)
                        .addComponent(txtGiaBan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CbDanhMucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbDanhMucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbDanhMucActionPerformed

    private void txtTenMonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenMonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenMonActionPerformed

    private void BtnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnHuyActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_BtnHuyActionPerformed

    private void lbHinhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbHinhMouseClicked
        this.selectImage();
    }//GEN-LAST:event_lbHinhMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
 
         if (unlityHelper.checkNullText(txtTenMon)) {
            if (unlityHelper.checkName(txtTenMon)) {
                if (unlityHelper.checkNullText(txtGiaBan)) {
                    if (unlityHelper.checkMoney(txtGiaBan)) {
                        if(checkNullHinh()){
                            selectImage();
                            insert();
                    }}
                }
            }
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void CbDanhMucItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CbDanhMucItemStateChanged

    }//GEN-LAST:event_CbDanhMucItemStateChanged

    void insert() {
        MonAn model = getModel();
        try {
            dao.insert(model);
            helper.dialogHelper.alert(this, "Thêm mới thành công");
        } catch (Exception e){
            helper.dialogHelper.alert(this, " Thêm mới thất bại");
        }

    }

    //lấy thông tin trên form điền vào đt
    MonAn getModel() {
        MonAn model = new MonAn();
        DanhMuc_duc dm = (DanhMuc_duc) comBoDanhMuc.getElementAt(CbDanhMuc.getSelectedIndex());
        model.setTenMon(txtTenMon.getText());
        model.setDonGia(Double.valueOf(txtGiaBan.getText()));
        model.setHinhAnh(lbHinh.getToolTipText());
        model.setMaDanhMuc(dm.getMaDanhMuc());
        model.setTrangThai(1);
        return model;
    }

    void selectImage() {
        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) { //nếu người dùng đã chọn đc file
            File file = fileChooser.getSelectedFile();    //lấy file người dùng chọn
            if (shareHelper.saveLogo(file)) {  //sao chép file đã chọn thư mục 
                // Hiển thị hình lên form
                lbHinh.setIcon(shareHelper.readLogo(file.getName())); //file.getName(); lấy tên của file
                //ImageIcon readLogo(String tenFile) đọc file trong thư mục logos theo tên file trả về ImageIcon
                //void setIcon(ImageIcon icon) set Icon cho lbl
                lbHinh.setToolTipText(file.getName());
            }
        }

    }

    public void loadDataToComBoDM() {
        comBoDanhMuc = (DefaultComboBoxModel) CbDanhMuc.getModel();
        dmd.LoadDataToComBoDanhMuc(comBoDanhMuc);
    }
//    public void loatMa(){
//      comBoDanhMuc = (DefaultComboBoxModel) CbDanhMuc.getModel();
//      dmd.loadMadm(comBoDanhMuc);
//    }
 public boolean checkNullHinh() {
        if (lbHinh.getToolTipText() != null) {
            return true;
        } else {
            dialogHelper.alert(this, "Không được để trống hình.");
            return false;
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemMonAn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemMonAn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemMonAn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemMonAn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemMonAn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnHuy;
    private javax.swing.JComboBox<String> CbDanhMuc;
    private javax.swing.JButton btnThem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lbHinh;
    private javax.swing.JTextField txtGiaBan;
    private javax.swing.JTextField txtTenMon;
    // End of variables declaration//GEN-END:variables

}
