/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlbancoffe;

import DAO.An.KhuVucDAO_An;
import Helper.shareHelper;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import java.awt.GridLayout;
import java.awt.Insets;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import miniForm.ThemBan1_An;
import miniForm.ThemBan2;
import model.Ban;
import model.KhuVuc;
import Helper.An.unlityHelper_An;

/**
 *
 * @author CHIEN
 */
public class QLKhuVuc_An extends javax.swing.JPanel {

    /**
     * Creates new form QLKhuVuc_An
     */
    List<Ban> lstBan = new ArrayList<>();
    DefaultComboBoxModel comBoMode;
    KhuVucDAO_An kvDAO = new KhuVucDAO_An();
    String khuvuc;

    public QLKhuVuc_An() {
        initComponents();
        init();
    }

    void init() {

        //
        //load dữ liệu vào các combo
        loadDataToComBoKV();

        //lấy danh sách bàn 
        loadDataToListBan();

        //
        LoadBanToPanel();

    }

    //tải danh sách khu vực
    //load comboKV
    public void loadDataToComBoKV() {
        comBoMode = (DefaultComboBoxModel) cbxKhuVuc.getModel();
        kvDAO.loadDataToComBoKhuVuc(comBoMode);
    }

    //tải danh sách bàn
    public void loadDataToListBan() {
        lstBan.removeAll(lstBan);
        lstBan = kvDAO.selectListBan();
    }
    //hiện bàn
    GridBagConstraints gbcBan = new GridBagConstraints();

    public void LoadBanToPanel() {
        gbcBan.insets = new Insets(10, 10, 10, 10);
        int x = 0, y = 0;
        pnBan.removeAll();
        //
        KhuVuc kv = (KhuVuc) comBoMode.getElementAt(cbxKhuVuc.getSelectedIndex());;
        //
        for (int i = 0; i < lstBan.size(); i++) {
            Ban ban = lstBan.get(i);

            Integer makv = ban.getMaKhuVuc();

            if (makv.equals(kv.getMaKhuVuc())) {

                gbcBan.gridx = x;
                gbcBan.gridy = y;
                ++x;
                if (x % 6 == 0) {
                    x = 0;
                    ++y;
                }
                pnBan.add(taoBan(ban), gbcBan);
            }
        }
        pnBan.validate();
        pnBan.repaint();
    }

    //tạo button ban
    public JButton taoBan(Ban ban) {
        JButton btBan = new JButton();
        btBan.setText(ban.getTenBan());
        btBan.setPreferredSize(new Dimension(100, 100));
        btBan.setIcon(shareHelper.getIcon());
        btBan.setBackground(Color.white);
        btBan.setVerticalTextPosition(JLabel.BOTTOM);
        btBan.setHorizontalTextPosition(JLabel.CENTER);

        //xử lý sự kiện
        btBan.addActionListener((ae) -> {
            lbTenBan.setText(btBan.getText());
            KhuVuc kv = (KhuVuc) comBoMode.getElementAt(cbxKhuVuc.getSelectedIndex());;
            int chon = JOptionPane.showConfirmDialog(this, "Xác nhận", "Bạn có muốn xoá bàn", JOptionPane.YES_NO_OPTION);
            if (chon == JOptionPane.YES_OPTION) {
                kvDAO.deleteBan(lbTenBan.getText(), kv.getMaKhuVuc(), 0);
                loadDataToListBan();
                LoadBanToPanel();
            }

        });
        return btBan;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnKhuVuc = new javax.swing.JPanel();
        cbxKhuVuc = new javax.swing.JComboBox<>();
        pnBan = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnThemKhuVuc = new javax.swing.JButton();
        btnXoaKhuVuc = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        btnXacNhan = new javax.swing.JButton();
        btnThemBan = new javax.swing.JButton();
        lbTenBan = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(1600, 900));
        setMinimumSize(new java.awt.Dimension(1600, 900));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(1600, 900));
        setLayout(new java.awt.GridLayout(1, 0));

        pnKhuVuc.setBackground(new java.awt.Color(107, 70, 52));
        pnKhuVuc.setMaximumSize(new java.awt.Dimension(1600, 900));
        pnKhuVuc.setMinimumSize(new java.awt.Dimension(1600, 900));
        pnKhuVuc.setPreferredSize(new java.awt.Dimension(1600, 900));

        cbxKhuVuc.setBackground(new java.awt.Color(204, 204, 255));
        cbxKhuVuc.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        cbxKhuVuc.setForeground(new java.awt.Color(107, 70, 52));
        cbxKhuVuc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Khu vực", "tầng 1", "tầng 2", "sân thượng" }));
        cbxKhuVuc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxKhuVucItemStateChanged(evt);
            }
        });
        cbxKhuVuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxKhuVucActionPerformed(evt);
            }
        });

        pnBan.setBackground(new java.awt.Color(212, 181, 152));
        pnBan.setLayout(new java.awt.GridBagLayout());

        jPanel4.setBackground(new java.awt.Color(107, 70, 52));
        jPanel4.setLayout(new java.awt.GridLayout(1, 2, 20, 0));

        btnThemKhuVuc.setBackground(new java.awt.Color(126, 199, 47));
        btnThemKhuVuc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnThemKhuVuc.setForeground(new java.awt.Color(255, 255, 255));
        btnThemKhuVuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/them.png"))); // NOI18N
        btnThemKhuVuc.setText("Thêm khu vực");
        btnThemKhuVuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemKhuVucActionPerformed(evt);
            }
        });
        jPanel4.add(btnThemKhuVuc);

        btnXoaKhuVuc.setBackground(new java.awt.Color(204, 0, 0));
        btnXoaKhuVuc.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnXoaKhuVuc.setForeground(new java.awt.Color(255, 255, 255));
        btnXoaKhuVuc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/huy.png"))); // NOI18N
        btnXoaKhuVuc.setText("Xóa khu vực");
        btnXoaKhuVuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaKhuVucActionPerformed(evt);
            }
        });
        jPanel4.add(btnXoaKhuVuc);

        jPanel5.setBackground(new java.awt.Color(107, 70, 52));
        jPanel5.setLayout(new java.awt.GridLayout(1, 3, 25, 20));

        btnXacNhan.setBackground(new java.awt.Color(29, 120, 115));
        btnXacNhan.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnXacNhan.setForeground(new java.awt.Color(255, 255, 255));
        btnXacNhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/dangNhap.png"))); // NOI18N
        btnXacNhan.setText("Xác nhận");
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });
        jPanel5.add(btnXacNhan);

        btnThemBan.setBackground(new java.awt.Color(126, 199, 47));
        btnThemBan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnThemBan.setForeground(new java.awt.Color(255, 255, 255));
        btnThemBan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/them.png"))); // NOI18N
        btnThemBan.setText("Thêm bàn");
        btnThemBan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btnThemBanItemStateChanged(evt);
            }
        });
        btnThemBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemBanActionPerformed(evt);
            }
        });

        lbTenBan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbTenBan.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/loadLai.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnKhuVucLayout = new javax.swing.GroupLayout(pnKhuVuc);
        pnKhuVuc.setLayout(pnKhuVucLayout);
        pnKhuVucLayout.setHorizontalGroup(
            pnKhuVucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnKhuVucLayout.createSequentialGroup()
                .addGroup(pnKhuVucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnKhuVucLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(pnKhuVucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnKhuVucLayout.createSequentialGroup()
                                .addComponent(cbxKhuVuc, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(89, 89, 89)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(lbTenBan, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(pnBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnKhuVucLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnThemBan, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnKhuVucLayout.setVerticalGroup(
            pnKhuVucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnKhuVucLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnKhuVucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxKhuVuc, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbTenBan, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pnBan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(pnKhuVucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThemBan, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        add(pnKhuVuc);
    }// </editor-fold>//GEN-END:initComponents

    private void cbxKhuVucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxKhuVucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxKhuVucActionPerformed

    //check định dạng

    private void btnThemKhuVucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemKhuVucActionPerformed
        khuvuc = JOptionPane.showInputDialog(this, "Tên khu vực");
        if (khuvuc.equals("")) {
            JOptionPane.showConfirmDialog(this, "không được để trống");
        } else {

            kvDAO.insertKV(khuvuc, 1);

        }


    }//GEN-LAST:event_btnThemKhuVucActionPerformed

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        // TODO add your handling code here:
        ManHinhBatDau bt = new ManHinhBatDau();
        GridLayout grl = new GridLayout();
        pnKhuVuc.setLayout(grl);
        pnKhuVuc.removeAll();
        pnKhuVuc.add(bt);
        pnKhuVuc.validate();
        pnKhuVuc.repaint();
    }//GEN-LAST:event_btnXacNhanActionPerformed

    private void btnThemBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemBanActionPerformed
        // TODO add your handling code here

        ThemBan1_An tb1 = new ThemBan1_An();
        tb1.setVisible(true);
        btnThemBan.setEnabled(false);
    }//GEN-LAST:event_btnThemBanActionPerformed
//chech bàn

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        btnThemBan.setEnabled(true);


    }//GEN-LAST:event_jLabel2MouseClicked

    private void cbxKhuVucItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxKhuVucItemStateChanged
        LoadBanToPanel();
    }//GEN-LAST:event_cbxKhuVucItemStateChanged

    private void btnXoaKhuVucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaKhuVucActionPerformed
        KhuVuc kv = (KhuVuc) comBoMode.getElementAt(cbxKhuVuc.getSelectedIndex());
        try {
            kvDAO.delete(kv.getTenKhuVuc(), 0);
            Helper.An.dialogHelper_An.alert(this, "Xoá thành công");
        } catch (Exception e) {
            Helper.An.dialogHelper_An.alert(this, "Xoá lỗi");
        }

    }//GEN-LAST:event_btnXoaKhuVucActionPerformed

    private void btnThemBanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnThemBanItemStateChanged
        loadDataToListBan();
        LoadBanToPanel();
    }//GEN-LAST:event_btnThemBanItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThemBan;
    private javax.swing.JButton btnThemKhuVuc;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JButton btnXoaKhuVuc;
    private javax.swing.JComboBox<String> cbxKhuVuc;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lbTenBan;
    private javax.swing.JPanel pnBan;
    private javax.swing.JPanel pnKhuVuc;
    // End of variables declaration//GEN-END:variables
}
